# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
